language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
sudo: enabled
dist: bionic
addons:
  apt:
    packages:
      - g++
      - coinor-cbc
      - coinor-libcbc-dev
install:
  - pip install cython numpy
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls --ignore-installed
script:
  - export NUMBA_DISABLE_JIT=1
  - coverage run alphamind/tests/test_suite.py
  - coverage report
  - coverage html
after_success:
  - coveralls
